export const ADD_BOOK = "BOOK_LIBRARY/ADD_BOOK";
export const ADD_CHECKED_BOOK = "BOOK_LIBRARY/ADD_CHECKED_BOOK";
export const REMOVE_BOOK = "BOOK_LIBRARY/REMOVE_BOOK";
export const REMOVE_CHECKED_BOOK = "BOOK_LIBRARY/REMOVE_CHECKED_BOOK";
export const REMOVE_BOOK_ALL = "BOOK_LIBRARY/REMOVE_BOOK_ALL";
